// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4oV543GxGOAAxgDIr-oCf7LQV1H53WrM',
    appId: '1:725363533702:web:118ed379b2cef3058aee07',
    messagingSenderId: '725363533702',
    projectId: 'mates-8238c',
    authDomain: 'mates-8238c.firebaseapp.com',
    storageBucket: 'mates-8238c.firebasestorage.app',
    measurementId: 'G-L2NRBZPPC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB72WUtD32Wb2lMNz0sdR8hD9mf_oOlJ3Y',
    appId: '1:725363533702:android:1c63808e43273c578aee07',
    messagingSenderId: '725363533702',
    projectId: 'mates-8238c',
    storageBucket: 'mates-8238c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAttHG15e7Xsq5-0MmHtiXIkEbMzqTpjoo',
    appId: '1:725363533702:ios:631a0c365df4204b8aee07',
    messagingSenderId: '725363533702',
    projectId: 'mates-8238c',
    storageBucket: 'mates-8238c.firebasestorage.app',
    iosBundleId: 'com.example.mates',
  );
}
